name: Test

on: [push]

jobs:
  showbug:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pip-version: [ 21.1, 21.2 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pip
      run: |
        python -m pip install pip==${{ matrix.pip-version }}
    - name: Install project dependencies
      run: |
        pip install -r req.txt
