name: Test

on: [push]

jobs:
  showbug:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pip-version: [ pip==21.1, pip==21.2, "git+git://github.com/notatallshaw/pip@third_attempt_at_prefer_non_conflicts" ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pip 
      run: |
        python -m pip install ${{ matrix.pip-version }}
    - name: Install project dependencies
      run: |
        pip install -r req.txt
